version: '3.8'

services:
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: api-postgres
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=api_db
  #   volumes:
  #     - ./local-database:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U postgres']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-demo-staging
    image: api-demo:staging
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: unless-stopped
