name = "api-demo-staging"
main = "src/index.ts"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_CODE = "gem_signal_demo_staging"
LOGGER_ENABLED = "true"
RATE_LIMIT_ENABLED = "true"
SWAGGER_ENABLED = "true"
DB_LOGGING_ENABLED = "true"
JWT_ISSUER = "gemsignal"
SWAGGER_CONTACT_NAME = "Thinh Tran"
SWAGGER_CONTACT_EMAIL = "thinhtran3588@gmail.com"
SWAGGER_CONTACT_URL = "https://thinhtq.com"
SWAGGER_PRODUCTION_URL = "https://api-demo-staging.gemsignal.com"
GRAPHIQL_ENABLED = "true"

[observability]
enabled = true
